name: mome

# Sampling
bias_sampling: False
preference_conditioned: False

# Emitter params
mutation_ga_batch_size: 256
mutation_qpg_batch_size: 0


# Polynomial mutation params
proportion_to_mutate: 0.6 # don't actually use this as purely crossover
eta: 1 
crossover_percentage: 1. 
