name: mome-pgx

# Sampling
bias_sampling: True
preference_conditioned: False

# Emitter params
mutation_ga_batch_size: 128
mutation_qpg_batch_size: 128
inject_actor_batch_size: 0
num_actor_active_samples: 0
