name: mome

# Sampling
bias_sampling: False
preference_conditioned: False

# Emitter params
mutation_ga_batch_size: 256
mutation_qpg_batch_size: 0
inject_actor_batch_size: 0
num_actor_active_samples: 0

# Polynomial mutation params
proportion_to_mutate: 0.6 # don't actually use this as purely crossover
eta: 1 
crossover_percentage: 1. 


# WandB Log Metrics
wandb_metrics_keys: [
    "moqd_score",
    "qd_sparsity_score",
    "max_hypervolume",
    "max_sum_scores",
    "coverage",
    "global_hypervolume",
    "global_sparsity",
    "total_num_solutions",
    "emitter_count",
]