name: nsga2

# Sampling
bias_sampling: False
preference_conditioned: False

# Emitter params
mutation_ga_batch_size: 128
mutation_qpg_batch_size: 0
inject_actor_batch_size: 0
num_actor_active_samples: 0

# Polynomial mutation params
proportion_to_mutate: 0.6 # don't actually use this as purely crossover
eta: 1 
crossover_percentage: 1. 

