name: pc-mome-pgx

# Sampling
bias_sampling: True
preference_conditioned: True

# Emitter params
mutation_ga_batch_size: 64
mutation_qpg_batch_size: 64

# Preferenced-conditioned actor hidden layer sizes
num_actor_active_samples: 32
pc_actor_uniform_preference_sampling: True
inject_actor_batch_size: 32

# Which sampling method to use for the preference conditioned policy gradient
sampler: "keep"
