name: pg-pc-mome-pgx

# Sampling
bias_sampling: True
preference_conditioned: True

# Emitter params
mutation_ga_batch_size: 128
mutation_qpg_batch_size: 128

# Preferenced-conditioned actor hidden layer sizes
num_actor_active_samples: 128
pc_actor_uniform_preference_sampling: True
inject_actor_batch_size: 64

# Which sampling method to use for the preference conditioned policy gradient
sampler: "prediction_guided"

# Hyperbolic Model params
hyperbolic_buffer_size: 128000
num_weight_candidates: 8
num_neighbours: 16
scaling_sigma: 0.1


# WandB Log Metrics
wandb_metrics_keys: [
    "moqd_score",
    "max_hypervolume",
    "max_sum_scores",
    "coverage",
    "global_hypervolume",
    "total_num_solutions",
    "emitter_ga_count",
    "emitter_actor_inject_count",  
    "emitter_pg_count",
    "pc_actor_f1_errors_correlation",
    "pc_actor_total_error",
]