name: pga

# Sampling
bias_sampling: True
preference_conditioned: False

# Emitter params
mutation_ga_batch_size: 64
mutation_qpg_batch_size: 64
inject_actor_batch_size: 0
num_actor_active_samples: 0
