name: ant_tri

num_descriptor_dimensions: 4
num_objective_functions: 3

# Min and max val of BDs
min_bd: 0. 
max_bd: 1.

# Min and Max values of rewards for reference points
# Empirically observed min rewards: [-533.27136, -875.678, -3945.274]
# Empirically observed max rewards: [4772.9199, 4711.7861, -0.8299942]
reference_point: [-1200, -1200, -4500]
max_fitnesses: [5000, 5000, 0]

# Min and Max values for rewards for normalisation
min_rewards: [-7, -7, -4.5]
max_rewards: [8, 8, 0]

# Empirical Maximum Hypervolume for the environment: 20053136.0
max_hypervolume: 210000000.0

# Normalisation/Standardisation of rewards
standardise_rewards: True
normalise_rewards: False