name: halfcheetah_tri

num_descriptor_dimensions: 2
num_objective_functions: 3

# Min and max val of BDs
min_bd: 0. 
max_bd: 1.

# Min and Max values of fitnesses for reference points
reference_point: [-2000, -2000, -800]

# Min and Max values for rewards for normalisation
# Empirical min:[-8.45081, -0.6]
# Empirical max:[12.42157, -0.0000000596]
min_rewards: [-9, -9, -0.65]
max_rewards: [13, 13, 0]

# Emperical Maximum Hypervolume for the environment: 5423918.0
max_hypervolume: 60000000.0

# Normalisation/Standardisation of rewards
standardise_rewards: True
normalise_rewards: False