name: hopper_multi

num_descriptor_dimensions: 1
num_objective_functions: 2

# Min and max val of BDs
min_bd: 0. 
max_bd: 1.

# Min and Max values of rewards for reference points
# Empirical min: [-35.17073, -2.3517342]
# Empirical max: [825.2477, -1.8515066-06]
reference_point: [-50, -3]
max_fitnesses: [1000, 0]

# Min and Max values of rewards for reference points
# Empirical min: [-3.792442, -0.003]
# Empirical max: [6.934434, 0]
min_rewards: [-5, -0.0035]
max_rewards: [8, 0]

# Empirical Maximum Hypervolume for the environment: 1891.3987
max_hypervolume: 2500.0

# Normalisation/Standardisation of rewards
standardise_rewards: True
normalise_rewards: False