name: hopper_multi

num_descriptor_dimensions: 1
num_objective_functions: 2

# Min and max val of BDs
min_bd: 0. 
max_bd: 1.

# Min and Max values of rewards for reference points
# Empirical min: [-35.17073, -1.3313142]
# Empirical max: [537.24084, -2.264291e-06]

min_rewards: [-0.05, -0.002]
max_rewards: [0.8, 0]
reference_point: [-50, -2]
