name: humanoid_tri

num_descriptor_dimensions: 2
num_objective_functions: 3

# Min and max val of BDs
min_bd: 0. 
max_bd: 1.

# Min and Max values of rewards for reference points
reference_point: [-100, -100, -500]

# Min and Max values of rewards for reference points
min_rewards: [-4.5, -4.5, -0.0035]
max_rewards: [8, 8, 0]


# Empirical Maximum Hypervolume for the environment: ### STILL TO DO
max_hypervolume: 25000.0

# Normalisation/Standardisation of rewards
standardise_rewards: True
normalise_rewards: False