name: walker2d_tri

num_descriptor_dimensions: 2
num_objective_functions: 3

# Min and max val of BDs
min_bd: 0. 
max_bd: 1.

# Min and Max values of fitnesses for reference points
reference_point: [-210, -210, -15]

# Min and Max values for rewards for normalisation
min_rewards: [-6, -6, -0.0065]
max_rewards: [8, 8, 0]

# Empirical Maximum Hypervolume for the environment: 40425.383
max_hypervolume: 500000.0

# Normalisation/Standardisation of rewards
standardise_rewards: True
normalise_rewards: False