name: walker2d_multi

num_descriptor_dimensions: 2
num_objective_functions: 2

# Min and max val of BDs
min_bd: 0. 
max_bd: 1.

# Min and Max values of fitnesses for reference points
# Empirical min: [-205.34937, -5.514009]
# Emprical max: [2186.4878, -1.3155421e-05]
reference_point: [-210, -15]
max_fitnesses: [2400, 0]

# Min and Max values for rewards for normalisation
# Empirical min: [-5.0035563, -0.006]
# Empirical max: [6.5805907, -0.000000000931]
min_rewards: [-6, -0.0065]
max_rewards: [8, 0]

# Empirical Maximum Hypervolume for the environment: 40425.383
max_hypervolume: 50000.0

# Normalisation/Standardisation of rewards
standardise_rewards: True
normalise_rewards: False